services:

  mysql:
    image: mysql:8.0
    container_name: ivolve-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  auth-service:
    build: ./auth-service
    container_name: ivolve-auth
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  roadmap-service:
    build: ./roadmap-service
    container_name: ivolve-roadmap
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: ivolve-frontend
    environment:
      AUTH_SERVICE_URL: http://auth-service:5000
      ROADMAP_SERVICE_URL: http://roadmap-service:8080
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - roadmap-service

volumes:
  mysql-data: