apiVersion: apps/v1
kind: Deployment
metadata:
  name: roadmap-service
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: roadmap-service
  template:
    metadata:
      labels:
        app: roadmap-service
    spec:
      containers:
        - name: roadmap-service
          image: 509989879328.dkr.ecr.us-east-1.amazonaws.com/ivolve-roadmap-service:latest
          ports:
            - containerPort: 8080
